[package]
name = "str-tests"
version = "0.0.0"
edition = "2021"

[dev-dependencies]
anyhow = "*"
colored = "2.0.0"
cradle = "*"
pretty_assertions = "*"
strip-ansi-escapes = "0.1.1"
tempfile = "*"
unindent = "*"
