[package]
name = "str"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "*"
cradle = "*"
esbuild-rs = "*"
tempfile = "*"
unindent = "*"

[dev-dependencies]
executable-path = "*"
pretty_assertions = "*"
